### Broadcasting ###

In [1]:
#https://numpy.org/doc/stable/user/basics.broadcasting.html

he term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

In [1]:
import numpy as np

In [2]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
a * b 

array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [13]:
a = np.array([1.0,2.0,3.0])
b = 2.0
c = a * b
c.dtype

dtype('float64')

In [15]:
a1 = np.array([[0.0,0.0,0.0],
             [10.0,10.0,10.0],
             [20.0,20.0,20.0],
             [30.0,30.0,30.0]])

b1 = np.array([[1.0,2.0,3.0]])



In [16]:
a1 + b1

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [17]:
b2 = np.array([10.0,20.0,30.0,40.0])
a1 +b2

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [18]:
b1 + a1

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [27]:
a2 = np.array([0.0,10.0,20.0,30.0])
b2 = np.array([1.0,2.0,3.0])
c2 = a[:,np.newaxis] + b
c2.shape
c2

array([[[ 1.,  2.,  3.]],

       [[11., 12., 13.]],

       [[21., 22., 23.]],

       [[31., 32., 33.]]])