In [1]:
#https://numpy.org/doc/stable/user/basics.types.html

Array types and conversions between types
NumPy supports a much greater variety of numerical types than Python does.
This section shows which are available, and how to modify an array’s data-type.

In [1]:
import numpy as np

In [3]:
x= np.float32(3.0)
x

3.0

In [6]:
y = np.int_([1,2,3])
y

array([1, 2, 3])

In [10]:
z = np.arange(3,dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [13]:
z = np.arange(3,dtype='f')
z

array([0., 1., 2.], dtype=float32)

To convert the type of an array, use the .astype() method (preferred) or the type itself as a function. For example:

In [14]:
z.astype(float)

array([0., 1., 2.])

In [15]:
np.int8(z)

array([0, 1, 2], dtype=int8)

In [17]:
z.dtype

dtype('float32')

In [18]:
d = np.dtype(int)
d

dtype('int32')

In [19]:
np.issubdtype(d,np.integer)

True

In [20]:
np.issubdtype(d,np.float32)

False

Array Scalars

In [23]:
np.power(100,8,dtype=np.int64)

10000000000000000

In [25]:
np.power(100,8,dtype=np.int32)

1874919424

The behaviour of NumPy and Python integer types differs significantly for integer overflows and may confuse users expecting NumPy integers to behave similar to Python’s int. Unlike NumPy, the size of Python’s int is flexible. This means Python integers may expand to accommodate any integer and will not overflow.

NumPy provides **numpy.iinfo** and **numpy.finfo** to verify the minimum or maximum values of NumPy integer and floating point values respectively

In [27]:
np.iinfo(int)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [28]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [30]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [31]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [32]:
np.power(100,100,dtype=np.int64)

0

In [34]:
np.power(100,100,dtype=np.float64)

1e+200