In [2]:
import numpy as np


In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[2]

2

In [14]:
x[-2]

8

In [17]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x[1,3]

8

In [21]:
x[1,-1]

9

In [22]:
x[0]

array([0, 1, 2, 3, 4])

In [23]:
x[0][2]

2

In [26]:
x = np.array([0,1,2,3,4,5,6,7,8,9,10])
x[1:8:2]

array([1, 3, 5, 7])

In [27]:
x[0:9:3]

array([0, 3, 6])

In [28]:
x[5:]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
x[:5]

array([0, 1, 2, 3, 4])

In [47]:
x = np.array([[[1],[2],[3]],[[4],[5],[6]]])
x.shape

(2, 3, 1)

In [31]:
x.shape

(2, 3, 1)

In [32]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [33]:
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
x[0,:,:]

array([[1],
       [2],
       [3]])

In [36]:
x[:,np.newaxis,:,:].shape

(2, 1, 3, 1)

In [37]:
#Simply put, numpy.newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus

In [17]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [18]:
a = x[:,np.newaxis]
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [19]:
b = x[np.newaxis,:]
b

array([[0, 1, 2, 3, 4]])

In [21]:
print((a + b).shape)
(a+b)

(5, 5)


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [46]:
#https://numpy.org/doc/stable/user/basics.indexing.html
#https://stackoverflow.com/questions/29241056/how-do-i-use-np-newaxis

In [1]:
#Advanced indexing

In [4]:
x = np.arange(10,1,-1)
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [6]:
x[np.array([3,3,1,7,8])]

array([7, 7, 9, 3, 2])

In [7]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
rows = np.array([[0,0],[3,3]])
column = np.array([[0,2],[0,2]])
y = x[rows,column]
y
                 

array([[ 0,  2],
       [ 9, 11]])

In [16]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
y = x[[0,1,2],[0,1,0]]
y

[[1 2]
 [3 4]
 [5 6]]


array([1, 4, 5])

In [26]:
x = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# Construct the following 2D array
# from the contents of `x`:
#
#     [[x[0, 0], x[0, 1]],
#      [x[2, 2], x[2, 2]]]

rows = np.array([[0,0],[2,2]])
cols = np.array([[0,1],[2,2]])
x[rows, cols]

array([[0, 1],
       [8, 8]])

In [28]:
#Indexing into 1-Dimensional Arrays
y = np.array([0,-1,-2,-3,-4,-5])
index = np.array([2,3,4,4])
y[index]

array([-2, -3, -4, -4])

In [33]:
#Boolean-Array Indexing
x1 = np.array([[[-0.26,  0.49,  0.18],
              [ 0.43,  0.3 ,  0.29],
           [-0.44,  0.3 ,  0.28],                [ 0.27, -0.09, -0.13]]])

In [30]:
bool_ind = x1>0
bool_ind

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [34]:
x[bool_ind]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
y = np.array([0,-1,-2,-3,-4,-5])
y

array([ 0, -1, -2, -3, -4, -5])

In [37]:
ind = np.array([1])
y[ind]

array([-1])

In [39]:
ind = np.array([1,2,1,0])
y[ind]

array([-1, -2, -1,  0])

In [41]:
ind3 = np.array([[0,5],
               [1,4]])
y[ind3]

array([[ 0, -5],
       [-1, -4]])

In [43]:
ind4 = np.array([[2],
                [3],
                [4]])
y[ind4]

array([[-2],
       [-3],
       [-4]])

In [44]:
#Integer Array Indexing (N-D): Solution

In [48]:
z = np.array([[[ 0,  1,  2,  3],
               [ 4,  5,  6,  7],
               [ 8,  9, 10, 11]],
              
           [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])   

In [50]:
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
ind0 = np.array([0,0,0,1,1,1]).reshape(2,3)
ind1 = np.array([0,1,2,0,1,2]).reshape(2,3)
#ind2 = np.array([0,1,2,0,1,2]).reshape(2,3)
print(ind1)
print("\n")
z[ind0,ind1,ind2]

[[0 1 2]
 [0 1 2]]




array([[ 0,  5, 10],
       [12, 17, 22]])

In [64]:
#Boolean Indexing: Solution
h = np.array([[ 0.01,  0.03,  0.1 ,  0.25],
 [ 0.38,  0.22,  0.15,  0.34],
[-0.29,  0.13, -0.26,  0.33]])
h

array([[ 0.01,  0.03,  0.1 ,  0.25],
       [ 0.38,  0.22,  0.15,  0.34],
       [-0.29,  0.13, -0.26,  0.33]])

In [65]:
h[h<0]

array([-0.29, -0.26])

In [67]:
h[np.logical_or(np.isclose(h,0.01),np.isclose(h,0.33))]

array([0.01, 0.33])