**Difference between Numpy array and Numpy matrix**

In [1]:
import numpy as np

res = np.array(['G','F','G'])
print("Numpy Array in python:",res)
print(type(res))

**What is numpy.matrix() in Python**

A matrix in Numpy returns a matrix from a string of data or array-like object. The matrix obtained is a specialized 2D array.

In [3]:
mat = np.matrix([
                [1,2,3],
                [5,6,7],
                [7,8,9]
                ])
print("Matrix is:\n", mat)
print(type(mat))

Matrix is:
 [[1 2 3]
 [5 6 7]
 [7 8 9]]
<class 'numpy.matrix'>


In [4]:
arr_mat = np.array([[23,34,55],
                   [56,65,67],
                   [90,88,21]])
print(arr_mat)
print(type(arr_mat))

[[23 34 55]
 [56 65 67]
 [90 88 21]]
<class 'numpy.ndarray'>


In [7]:
arr1 = np.array([1,2,3])
print("1D Array\n",arr1)
print("\n")

arr2 = np.array([[1,2],[3.4]])
print("2D Array\n",arr2)

C = np.array([[[1, 2], [3, 4]],
             [[5, 6], [7, 8]],
             [[9, 10], [11, 12]]])
print("3D array\n", C)

1D Array
 [1 2 3]


2D Array
 [list([1, 2]) list([3.4])]
3D array
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


C:\Users\srini\AppData\Local\Temp\ipykernel_19960\806358476.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1,2],[3.4]])


Matrix works normally for a 2D matrix and if a 1D matrix will convert into 2D Matrix, but if we pass a 3D matrix it will through an error.

In [17]:
arr1 = np.matrix([1,2,3])
print(arr1)
print("Dimensions:\t",arr1.ndim)
print("Shape:\t",arr1.shape)
print("\n")

arr2 = np.matrix([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print("2D Array is\n:",arr2)

[[1 2 3]]
Dimensions:	 2
Shape:	 (1, 3)


2D Array is
: [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


***Different functionality of  * operator in ndarray and Matrix***

In [18]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[5,6]])

c = a*b
print("Array multiplcation:\n",c)

Array multiplcation:
 [[ 2  6]
 [15 24]]


In [19]:
#While it does matrix multiplication.
a = np.matrix([[1,2],[3,4]])

b = np.matrix([[1,2],[3,4]])

c = a * b
print("Matrix multiplcation\n", c)


Matrix multiplcation
 [[ 7 10]
 [15 22]]


In [20]:
***Matrix has an array.I for inverse, but ndarray has linalg.inv***

SyntaxError: invalid syntax (1689433279.py, line 1)

In [22]:
#The inverse can be done with array.I in ndarray.
arr1 = np.matrix([[1,2],[3,4]])

print('Inverse \n',arr1.I)


Inverse 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
#The inverse can be done with np.linalg.inv in matrix.
arr1 = np.matrix([[1,2],[3,4]])

print("Inverse\n",np.linalg.inv(arr1))
#https://numpy.org/doc/stable/reference/routines.linalg.html

Inverse
 [[-2.   1. ]
 [ 1.5 -0.5]]
