In [11]:
import numpy as np


In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[2]

2

In [14]:
x[-2]

8

In [17]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
x[1,3]

8

In [21]:
x[1,-1]

9

In [22]:
x[0]

array([0, 1, 2, 3, 4])

In [23]:
x[0][2]

2

In [26]:
x = np.array([0,1,2,3,4,5,6,7,8,9,10])
x[1:8:2]

array([1, 3, 5, 7])

In [27]:
x[0:9:3]

array([0, 3, 6])

In [28]:
x[5:]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
x[:5]

array([0, 1, 2, 3, 4])

In [47]:
x = np.array([[[1],[2],[3]],[[4],[5],[6]]])
x.shape

(2, 3, 1)

In [31]:
x.shape

(2, 3, 1)

In [32]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [33]:
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
x[0,:,:]

array([[1],
       [2],
       [3]])

In [36]:
x[:,np.newaxis,:,:].shape

(2, 1, 3, 1)

In [37]:
#Simply put, numpy.newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus

In [39]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [43]:
a = x[:,np.newaxis]

In [44]:
b = x[np.newaxis,:]

In [50]:
(a + b).shape
(a+b)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [46]:
#https://numpy.org/doc/stable/user/basics.indexing.html
#https://stackoverflow.com/questions/29241056/how-do-i-use-np-newaxis

In [ ]:
#Advanced indexing