#### Vectors, the 1D Arrays ####

**Vector initialization:**
One way to create a NumPy array is to convert a Python list. The type will be auto-deduced from the list element types:

In [1]:
import numpy as np

In [13]:
a= np.array([1.,2.,3.])

In [14]:
b = np.zeros(3,int)
b

array([0, 0, 0])

In [15]:
b.dtype

dtype('int32')

In [16]:
type(b)

numpy.ndarray

In [18]:
a1 = np.zeros_like(a)
a1

array([0., 0., 0.])

In [19]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [21]:
arr = np.arange(2,8)
arr

array([2, 3, 4, 5, 6, 7])

In [26]:
arr = np.arange(1,6,2)
arr

array([1, 3, 5])

In [27]:
lin = np.linspace(0,5,8)
lin

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [29]:
lin = np.linspace(0,1,8)
lin

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [30]:
np.random.randint(0,10,3) #old.style

array([8, 6, 9])

In [34]:
np.random.rand(3) #Old style

array([0.60791511, 0.51737775, 0.06894342])

In [35]:
rng = np.random.default_rng()

In [45]:
print(rng.integers(0,10,3,endpoint= True))

[ 4 10 10]


In [48]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [49]:
a[1]

2

In [50]:
a[2:4]

array([3, 4])

In [52]:
a[-2:]

array([4, 5])

In [53]:
a[::3]

array([1, 4])

In [64]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

In [57]:
np.any(a>5)

True

In [58]:
np.all(a>5)

False

In [59]:
a[a>5]

array([6, 7, 6])

In [60]:
a[a > 5] = 0

In [61]:
a[(a >=3) & (a <=5)]

array([3, 4, 5, 5, 4, 3])

In [65]:
np.where(a > 5)

(array([5, 6, 7], dtype=int64),)

In [66]:
np.nonzero(a >5)

(array([5, 6, 7], dtype=int64),)

In [67]:
np.clip(a,2,5)

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

In [68]:
a1 = np.array([2,3])
a1

array([2, 3])

In [74]:
a2 = a1**2
a2

array([4, 9])

In [75]:
np.sqrt(a2)

array([2., 3.])

In [77]:
ae = np.exp(a1)
ae

array([ 7.3890561 , 20.08553692])

In [78]:
np.log(a1)

array([0.69314718, 1.09861229])

In [80]:
a.sort()

In [82]:
mul = np.random.randint(0,10,(3,2))
mul

array([[1, 7],
       [3, 7],
       [9, 8]])

In [83]:
mul = np.random.rand(3,2)
mul

array([[0.02715892, 0.71070601],
       [0.15671589, 0.85741406],
       [0.254999  , 0.95466703]])

In [85]:
mul = np.random.randn(3,2)
mul

array([[-0.26543669, -2.31357522],
       [-0.12845575,  0.2827513 ],
       [ 1.01625748,  1.03426132]])

In [88]:
mul = np.random.uniform(1,10,(2,3))
mul

array([[4.61567722, 9.00948242, 7.67990462],
       [8.83639145, 4.11507903, 6.71412148]])

In [89]:
mul = np.random.normal(10,2,(3,2))
mul

array([[ 7.16562731,  6.99616991],
       [10.29534631,  8.22872976],
       [ 9.62257173,  9.5091892 ]])

In [95]:
a = np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [96]:
#https://www.youtube.com/watch?v=a8aDcLk4vRc&t=9s&ab_channel=codebasics

In [97]:
a = np.array([[1,2],[4,5],[5,6]])
a

array([[1, 2],
       [4, 5],
       [5, 6]])

In [98]:
a.shape

(3, 2)

In [99]:
a.reshape(2,3)

array([[1, 2, 4],
       [5, 5, 6]])

In [100]:
a.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [5],
       [6]])

In [101]:
a.ravel()

array([1, 2, 4, 5, 5, 6])

In [102]:
a.sum(axis=1)

array([ 3,  9, 11])

In [103]:
a.sum(axis =0)

array([10, 13])

In [104]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.23606798, 2.44948974]])

In [105]:
np.std(a)

1.7716909687891083

In [2]:
#https://www.youtube.com/watch?v=_d_Ka-ks2a0&ab_channel=codebasics

In [3]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [4]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [5]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
np.stack((a,b))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [8]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [9]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
result = np.hsplit(a,3)

In [13]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [14]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [15]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [16]:
result[3]

IndexError: list index out of range

In [17]:
result = np.vsplit(a,2)

In [18]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [19]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
a3 = np.arange(12).reshape(3,4)
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
b = a3 > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
a3[b] # elements which are greater than 4 will display

array([ 5,  6,  7,  8,  9, 10, 11])

In [26]:
a3[b] = -1 #any elemenet greater that 4 is replace by -1
a3

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [27]:
c1 = np.arange(12).reshape(3,4)

In [28]:
c1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
for row in c1:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [30]:
for row in c1:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
#another way to aviod 2 for loops
for cell  in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [34]:
for x in np.nditer(c1,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [36]:
#https://numpy.org/doc/stable/reference/generated/numpy.nditer.html
for x in np.nditer(c1,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [39]:
for x in np.nditer(c1,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [40]:
for x in np.nditer(a3,op_flags=['readwrite']):
    x[...] = x *x
a3

array([[ 0,  1,  4,  9],
       [16,  1,  1,  1],
       [ 1,  1,  1,  1]])

In [49]:
b2 = np.arange(3,15,4).reshape(3,1)
b2

array([[ 3],
       [ 7],
       [11]])

In [60]:
b3 = np.arange(5,15,4).reshape(3,1)
b3

array([[ 5],
       [ 9],
       [13]])

In [62]:
for x,y in np.nditer([b2,b3]):
    print(x,y)

3 5
7 9
11 13
