### Structured arrays

In [1]:
#https://numpy.org/doc/stable/user/basics.rec.html

Structured arrays are ndarrays whose datatype is a composition of simpler datatypes organized as a sequence of named fields. For example,

In [3]:
import numpy as np

In [6]:
x = np.array([('Rex',9,81.0),('Fed',3,27.0)],dtype=[('names','U10'),('age','i4'),('weight','f4')])
x

array([('Rex', 9, 81.), ('Fed', 3, 27.)],
      dtype=[('names', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [7]:
x[1]

('Fed', 3, 27.)

In [8]:
x['age']

array([9, 3])

In [11]:
x['age'] = ([15,25])

In [12]:
x

array([('Rex', 15, 81.), ('Fed', 25, 27.)],
      dtype=[('names', '<U10'), ('age', '<i4'), ('weight', '<f4')])

**Assignment from Python Native Types (Tuples)**
The simplest way to assign values to a structured array is using python tuples. Each assigned value should be a tuple of length equal to the number of fields in the array, and not a list or array as these will trigger numpy’s broadcasting rules. The tuple’s elements are assigned to the successive fields of the array, from left to right:

In [15]:
x1 = np.zeros(2,dtype='i8,f4,?,S1')
x1[:] = 3
x1

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [16]:
#Structured Datatype Creation

In [17]:
np.dtype([('x','f4'),('y',np.float32),('z','f4',(2,2))])

dtype([('x', '<f4'), ('y', '<f4'), ('z', '<f4', (2, 2))])

If fieldname is the empty string '', the field will be given a default name of the form f#, where # is the integer index of the field, counting from 0 from the left:

In [18]:
np.dtype([('x','f4'),('','i4'),('z','i8')])

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

In [19]:
np.dtype([('x','f4'),('','i4'),('z','i8')])

dtype([('x', '<f4'), ('f1', '<i4'), ('z', '<i8')])

In [20]:
    np.dtype('i8,f4,S3')
    

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', 'S3')])

In [21]:
np.dtype('3int8,float32,(2,3)float64')

dtype([('f0', 'i1', (3,)), ('f1', '<f4'), ('f2', '<f8', (2, 3))])

The dictionary has two required keys, ‘names’ and ‘formats’, and four optional keys, ‘offsets’, ‘itemsize’, ‘aligned’ and ‘titles’. The values for ‘names’ and ‘formats’ should respectively be a list of field names and a list of dtype specifications, of the same length. The optional ‘offsets’ value should be a list of integer byte-offsets, one for each field within the structure. If ‘offsets’ is not given the offsets are determined automatically. The optional ‘itemsize’ value should be an integer describing the total size in bytes of the dtype, which must be large enough to contain all the fields.

In [23]:
np.dtype({'names':['col1','col2'],'formats':['i4','f4']})

dtype([('col1', '<i4'), ('col2', '<f4')])

In [25]:
np.dtype({'names':['col1','col2'],
         'formats':['i4','f4'],
         'offsets':[0,4],
         'itemsize':12})

dtype({'names': ['col1', 'col2'], 'formats': ['<i4', '<f4'], 'offsets': [0, 4], 'itemsize': 12})

In [29]:
np.array({'col1':('i1',0),'col2':('f4',1)})

array({'col1': ('i1', 0), 'col2': ('f4', 1)}, dtype=object)

In [1]:
#Manipulating and Displaying Structured Datatypes

The list of field names of a structured datatype can be found in the names attribute of the dtype object:

In [4]:
d = np.dtype([('x','i8'),('y','f4')])
d.names

('x', 'y')

In [5]:
d.fields

mappingproxy({'x': (dtype('int64'), 0), 'y': (dtype('float32'), 8)})

The dtype object also has a dictionary-like attribute, fields, whose keys are the field names (and Field Titles, see below) and whose values are tuples containing the dtype and byte offset of each field.

In [9]:
def offset_print(d):
    print("offset:",[d.fields[name][1] for name in d.names])
    print("itemsize:",d.itemsize)
offset_print(np.dtype('u1,u1,i4,u1,i4,u2'))

offset: [0, 1, 2, 6, 7, 11]
itemsize: 13


In [10]:
offset_print(np.dtype('u1,u1,i4,u1,i4,u2',align=True))

offset: [0, 1, 4, 8, 12, 16]
itemsize: 20


**Field Titles**

In addition to field names, fields may also have an associated title, an alternate name, which is sometimes used as an additional description or alias for the field. The title may be used to index an array, just like a field name.

In [11]:
np.dtype([(("my title","name"),'f4')])

dtype([(('my title', 'name'), '<f4')])

In [12]:
np.dtype({'name':('i4',0,'my title')})

dtype([(('my title', 'name'), '<i4')])

In [16]:
for name in d.names:
    print(d.fields[name][:2])
    

(dtype('int64'), 0)
(dtype('float32'), 8)


### Indexing and Assignment to Structured arrays ###

**Assigning data to a Structured Array**

There are a number of ways to assign values to a structured array: Using python tuples, using scalar values, or using other structured arrays.

*Assignment from Python Native Types (Tuples)*

In [17]:
x = np.array([(1,2,3),(4,55,55)],dtype='i8,f4,f8')
x

array([(1,  2.,  3.), (4, 55., 55.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [19]:
x[0].dtype

dtype([('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [22]:
x[1] =(555,555,555)
x

array([(  1,   2.,   3.), (555, 555., 555.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

*Assignment from Scalars*

A scalar assigned to a structured element will be assigned to all fields. This happens when a scalar is assigned to a structured array, or when an unstructured array is assigned to a structured array:


In [23]:
x3 = np.zeros(2,dtype='i8,f4,?,S1')
x3

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [26]:
x3[:] = 3
x3

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [27]:
twofields = np.zeros(2,dtype=[("A","i4"),("b","i4")])
twofields

array([(0, 0), (0, 0)], dtype=[('A', '<i4'), ('b', '<i4')])

In [28]:
onefields = np.zeros(2,dtype=[("A","i4")])
onefields

array([(0,), (0,)], dtype=[('A', '<i4')])

In [30]:
threefields = np.zeros(3,dtype=[("A","i4"),("B","f4"),("C","?")])
threefields

array([(0, 0., False), (0, 0., False), (0, 0., False)],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', '?')])

In [33]:
nostrct = np.zeros(2,dtype='i4')
nostrct

array([0, 0])

In [34]:
nostrct[:]=twofields


TypeError: Cannot cast array data from dtype([('A', '<i4'), ('b', '<i4')]) to dtype('int32') according to the rule 'unsafe'

In [36]:
de = np.array([1,2,3,4,5])
de

array([1, 2, 3, 4, 5])

In [37]:
de[1]

2

In [40]:
de[:]

array([1, 2, 3, 4, 5])

*Assignment from other Structured Arrays*

In [7]:
x = np.array([(1,2,3),(4,5,6)],dtype='i8,f4,f8')
x
x[1] = (7,8,9)
x

array([(1, 2., 3.), (7, 8., 9.)],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '<f8')])

In [8]:
x1 = np.zeros(2,dtype='i8,f4,?,S1')
x1

array([(0, 0., False, b''), (0, 0., False, b'')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [10]:
x1[:]= 3
x1

array([(3, 3.,  True, b'3'), (3, 3.,  True, b'3')],
      dtype=[('f0', '<i8'), ('f1', '<f4'), ('f2', '?'), ('f3', 'S1')])

In [19]:
x2 = np.zeros(3,dtype=[('a','i8'),('b','f4'),('c','S3')])
x2
x3 = np.ones(3,dtype=[('x','f4'),('y','S3'),('z','O')])
x3
             

array([(1., b'1', 1), (1., b'1', 1), (1., b'1', 1)],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

In [20]:
x3[:]=x2

In [21]:
x3

array([(0., b'0.0', b''), (0., b'0.0', b''), (0., b'0.0', b'')],
      dtype=[('x', '<f4'), ('y', 'S3'), ('z', 'O')])

**Indexing Structured Arrays**

Accessing Individual Fields

In [22]:
x = np.array([(1,2),(3,4)],dtype=[('foo','i8'),('bar','f4')])
x

array([(1, 2.), (3, 4.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

In [23]:
x['foo']

array([1, 3], dtype=int64)

In [26]:
x['foo'] = ([10,11])

In [27]:
x['foo']

array([10, 11], dtype=int64)

In [28]:
y =x['foo']
y

array([10, 11], dtype=int64)

In [30]:
y[:]= 11
y

array([11, 11], dtype=int64)

In [31]:
y.dtype

dtype('int64')

In [32]:
y.shape

(2,)

In [33]:
y.strides

(12,)

In [35]:
x =np.zeros((2,2),dtype=[('a',np.int32),('b',np.float64,(3,3))])
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [36]:
x.shape

(2, 2)

In [41]:
x['a'].shape

(2, 2)

In [44]:
a = np.zeros(3,dtype=[('a','i4'),('b','i4'),('c','f4')])
a
a[['a','c']]

array([(0, 0.), (0, 0.), (0, 0.)],
      dtype={'names': ['a', 'c'], 'formats': ['<i4', '<f4'], 'offsets': [0, 8], 'itemsize': 12})

In [50]:
b = np.zeros(3,dtype=[('x','f4'),('y','f4'),('z','f4')])
b[['x','z']].view('i4')

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

**Indexing with an Integer to get a Structured Scalar**