In [1]:
# Python program for
# iterating over array
import numpy as np

In [3]:
# creating an array using arrange 
# method
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
print("Modified array is:")

Modified array is:


In [6]:
for x in np.nditer(a):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
# creating an array using arrange 
# method
a = np.arange(12)
# shape array with 3 rows and 
# 4 columns
a = a.reshape(3,4)
print(a)
print('Modified array in C-style order:')
# iterating an array in a given
# order 
for x in np.nditer(a,order='C'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified array in C-style order:
0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
a = np.arange(12).reshape(3,4)
print(a)
print('Modified array in F-style order:')
for x in np.nditer(a,order='F'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified array in F-style order:
0
4
8
1
5
9
2
6
10
3
7
11


***Modifying Array Values:***

The nditer object has another optional parameter called op_flags.
Its default value is read-only, but can be set to read-write
or write-only mode.This will enable modifying array elements using this iterator.

In [14]:
a = np.arange(12).reshape(3,4)
print("Original array is:")
print(a)
# modifying array values
for x in np.nditer(a,op_flags =['readwrite']):
    x[...] = 5 *x
print("Modified array is:")
print(a)


Original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [20]:
a = np.arange(12)
a = a.reshape(3,4)
print(a)
print('Modified array is:',end='\n')
for x  in np.nditer(a,flags=['external_loop'], order = 'C'):
    print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Modified array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


a = np.arange(6)
a=a.reshape(2,3)
print(a)
it = np.nditer(a, flags=['f_index'])
while not it.finished:
    print("%d <%d>"% (it[0],it.index),end =" ")
    it.iternext()

***Broadcasting Iteration:***
    
If two arrays are broadcastable, a combined nditer object is able
to iterate upon them concurrently. Assuming that an array a has dimension 3X4, 
and there is another array b of dimension 1X4, the iterator of following
type is used (array b is broadcast to size of a).

In [24]:
# Python program for
# iterating array
a=np.arange(12)
a=a.reshape(3,4)
print("First array is:")
print(a)
print()
# Creating second array using 
# array method
print('Second array is:')
b = np.array([5,6,7,8],dtype =int)
print(b)
print()

print("Modified array is :",end ='\n')
for x,y in np.nditer([a,b]):
    print("%d:%d" %(x,y))
    


First array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Second array is:
[5 6 7 8]

Modified array is :
0:5
1:6
2:7
3:8
4:5
5:6
6:7
7:8
8:5
9:6
10:7
11:8
