### NumPy: the absolute basics for beginners ###

NumPy (Numerical Python) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. Learn more about NumPy at What is NumPy, and if you have comments or suggestions, please reach out!

(https://numpy.org/devdocs/user/absolute_beginners.html)

In [50]:
import numpy as np

<b>What is an “array”?</b>

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

Most NumPy arrays have some restrictions. For instance:

All elements of the array must be of the same type of data.

Once created, the total size of the the array can’t change.

The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

For the remainder of this document, we will use the word “array” to refer to an instance of ndarray.

#### Array fundamentals

In [51]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [52]:
#Like the original list, the array is mutable.
a[0]= -10

In [53]:
a

array([-10,   2,   3,   4,   5,   6])

In [54]:
#Also like the original list, Python slice notation can be used for indexing.

In [57]:
a[:3]

array([99, 99, 99])

In [58]:
a[:3] = [99,99,99]

In [59]:
a

array([99, 99, 99,  4,  5,  6])

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [9]:
b = a[3:]
b

array([4, 5, 6])

In [10]:
b[0] = 46

In [11]:
    a

array([99, 99, 99, 46,  5,  6])

Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [12]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 NumPy, a dimension of an array is sometimes referred to as an “axis”. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array a could represent three points, each lying within a four-dimensional space, but a has only two “axes”.

In [13]:
a1[1,3]

8

<b>Array attributes</b>

This section covers the ndim, shape, size, and dtype attributes of an array.

In [14]:
#The number of dimensions of an array is contained in the ndim attribute.
a1.ndim

2

In [15]:
#The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
a1.shape

(3, 4)

In [16]:
len(a1.shape) == a1.ndim

True

In [17]:
#The fixed, total number of elements in array is contained in the size attribute.
a1.size

12

In [18]:
import math
a.size == math.prod(a.shape)

True

In [19]:
#Arrays are typically “homogeneous”, meaning that they contain elements of only one 
#“data type”. The data type is recorded in the dtype attribute.
a1.dtype

dtype('int32')

In [20]:
## "int" for integer, "64" for 64-bit

The built-in math.prod() function from the math module in Python is used to return the products of elements in an iterable object like a list or a tuple.

math.prod(iterable, start)

In [60]:
liat_1 = [1,2,3,4]
print(math.prod(liat_1))
liat_2 = [3,3,3,3,3]
print(math.prod(liat_2))

24
243


In [61]:
#Empty iterable passed as an argument
list_3 = []
print(math.prod(list_3))
print(math.prod(list_3,start=3))

1
3


(https://www.educative.io/answers/what-is-mathprod-in-python)

<b>How to create a basic array</b>

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [62]:
a.dtype


dtype('int32')

<b>How to create a basic array</b>

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [63]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Or an array filled with 1’s:

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [66]:
# Create an empty array with 2 elements
np.empty(2)   # may vary

array([1.12526648e+169, 1.81771474e-280])

You can create an array with a range of elements:

In [67]:
np.arange(4)

array([0, 1, 2, 3])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [68]:
np.arange(2,9,2)

array([2, 4, 6, 8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [69]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [70]:
x = np.ones(2,dtype=np.int64)
x

array([1, 1], dtype=int64)

<b>Adding, removing, and sorting elements</b>

This section covers np.sort(), np.concatenate()

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [71]:
arr = np.array([2,0,1,33,14,3,99,100,74,25])


In [32]:
np.sort(arr)

array([  0,   1,   2,   3,  14,  25,  33,  74,  99, 100])

argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort.

You can concatenate them with np.concatenate().

In [33]:
a = np.array([1,2,3,4,5])
b = np.sort([6,7,8,9,11])
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

<b>How do you know the shape and size of an array?</b>

<b>ndarray.ndim</b> will tell you the number of axes, or dimensions, of the array.

<b>ndarray.size</b> will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

<b>ndarray.shape</b> will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [72]:
arr_exx = np.array([[[0,1,2,3],
                     [4,5,6,7]],
                     
                    [[0,1,2,3],
                    [4,5,6,7]],
                     
                    [[0,1,2,3],
                    [4,5,6,7]]
                   ])

In [73]:
arr_exx.ndim

3

In [74]:
arr_exx.shape

(3, 2, 4)

In [75]:
arr_exx.size

24

In [76]:
arr12 = np.array([[1,2,3],[4,5,6]])
arr12

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr12.shape

(2, 3)

In [78]:
arr12.ndim

2

In [79]:
arr12.size

6

<b>Can you reshape an array?</b>

This section covers arr.reshape()

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [80]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [81]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

With np.reshape, you can specify a few optional parameters:

newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

In [82]:
np.reshape(a,newshape=(1,6),order='C')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example, if you start with this array:

In [83]:
z = np.array([1,2,3,4,5,6])
z

array([1, 2, 3, 4, 5, 6])

In [84]:
z.shape

(6,)

You can use np.newaxis to add a new axis:

In [86]:
z1 = z[np.newaxis,:]
z1

array([[1, 2, 3, 4, 5, 6]])

In [87]:
z1.shape

(1, 6)

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [88]:
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

Or, for a column vector, you can insert an axis along the second dimension:

In [90]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

For example, if you start with this array:

In [91]:
z2 = np.array([1,2,3,4,5,6])
z2.shape

(6,)

You can use np.expand_dims to add an axis at index position 1 with:

In [97]:
z3 = np.expand_dims(z2,axis=1)
z3.shape

(6, 1)

In [98]:
z3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

You can add an axis at index position 0 with:

In [100]:
z4 = np.expand_dims(a,axis=0)
z4

array([[0, 1, 2, 3, 4, 5]])

Indexing and slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.